# -*- coding: utf-8 -*-
"""Acc TNS1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1XOiPOE0WWFCGXY3ALsJqyGjDv3Ruy3Em
"""

# Commented out IPython magic to ensure Python compatibility.
import numpy as np              # random numbers + array math
import pandas as pd             # DataFrames - the table both libraries plot from
import matplotlib.pyplot as plt # matplotlib
import seaborn as sns           # seaborn (built on matplotlib)

# show plots inline in the notebook:
# %matplotlib inline
np.random.seed(42)               # same "random" numbers every run

# One dataset for the whole notebook: daily sales for a coffee shop chain
dates = pd.date_range("2024-01-01", "2024-12-31", freq="D")   # every day in 2024
cities = ["Boston", "Austin", "Seattle", "Denver"]
categories = ["Coffee", "Tea", "Smoothie", "Pastry"]
price = {"Coffee": 4.5, "Tea": 3.5, "Smoothie": 5.5, "Pastry": 3.0}

rows = []
for d in dates:
    month = d.month
    seasonal_temp = 50 + 30 * np.sin((month - 1) / 12 * 2 * np.pi - np.pi / 2)  # warm in summer, cold in winter
    for city in cities:
        city_offset = {"Boston": -5, "Austin": 15, "Seattle": -8, "Denver": 2}[city]
        temp = seasonal_temp + city_offset + np.random.normal(0, 4)             # this city's temp today
        for cat in categories:
            base = {"Coffee": 220, "Tea": 90, "Smoothie": 60, "Pastry": 130}[cat]
            temp_effect = 0
            if cat == "Smoothie":
                temp_effect = (temp - 60) * 1.8      # smoothies sell more when hot
            elif cat == "Coffee":
                temp_effect = (60 - temp) * 0.9      # coffee sells more when cold
            sales = max(0, base + temp_effect + np.random.normal(0, 18))
            rating = np.clip(np.random.normal(4.2, 0.4), 1, 5)
            num_customers = max(0, sales / price[cat] + np.random.normal(0, 4))
            rows.append([d, city, cat, round(temp, 1), round(sales, 2), round(rating, 2), round(num_customers)])

df = pd.DataFrame(rows, columns=["date", "city", "category", "avg_temp", "daily_sales", "rating", "num_customers"])
df["month"] = df["date"].dt.month_name().str[:3]        # "Jan", "Feb", ...
df["day_of_week"] = df["date"].dt.day_name()             # "Monday", "Tuesday", ...
df["is_weekend"] = df["day_of_week"].isin(["Saturday", "Sunday"])

month_order = ["Jan","Feb","Mar","Apr","May","Jun","Jul","Aug","Sep","Oct","Nov","Dec"]
day_order = ["Monday","Tuesday","Wednesday","Thursday","Friday","Saturday","Sunday"]

print(df.shape)
df.head()

# OUR WORK
# 1. Line chart: total sales by month, but for Boston only
#    hint: filter df to city == "Boston" before grouping by month
# ...

# 2. Bar chart: total sales by CITY instead of by category
# ...

# 3. Histogram: distribution of "rating" instead of "daily_sales"
# ...

#line
Boston_monthly_total = df[df['city'] == 'Boston'].groupby("month",sort=False)["daily_sales"].sum().reindex(month_order)

plt.figure(figsize=(7,4))
plt.plot(monthly_total.index, monthly_total.values)
plt.title("Total Sales of boston by month")
plt.show()

#BAR CHART
totals_by_city = df.groupby("city")["daily_sales"].sum().sort_values(ascending=False)
plt.figure(figsize=(7,4))
plt.bar(totals_by_city.index , totals_by_city.values)
plt.title("Total sales by city")
plt.show()

# HISTOGRAM
plt.figure(figsize=(7, 4))
plt.hist(df["rating"], bins=40)   # 30 buckets across the range of daily_sales
plt.title("Distribution of Rating")
plt.xlabel("Ratings ($)")
plt.ylabel("Frequency")
plt.show()

# 1. Rebuild the Coffee vs. Smoothie line chart, but use Tea vs. Pastry instead
# ...

# 2. Add gridlines and an annotation marking the LOWEST month, not the peak
#    hint: idxmin() / min() instead of idxmax() / max()
# ...

# 3. Build a 1x2 (not 2x2) subplot grid comparing just Coffee and Tea
# ...

#1.LABELS + LEGEND + COLORS/STYLES/MARKERS, together
from numpy._core.fromnumeric import amax
Tea_trend = df[df.category == "Tea"].groupby("month",sort=False)["daily_sales"].sum().reindex(month_order)
Pastry_trend =  df[df.category == "Pastry"].groupby("month", sort=False)["daily_sales"].sum().reindex(month_order)

fig, ax = plt.subplots(figsize=(8,4.5))
ax.plot(Tea_trend.index , Tea_trend.values,
        color = "#004E64", linestyle = "-.", marker = "o", label ="Tea")
ax.plot(Pastry_trend.index , Pastry_trend.values,
        color = "#F79256" , linestyle = "-", marker = "h" , label ="pastry" )
ax.set_title("monthly sales of Tea vs Pastry")
ax.legend()
ax.plot()

#2 GRID & ANNOTATION
fig, ax = plt.subplots(figsize=(8,4.5))
ax.plot(Tea_trend.index , Tea_trend.values, marker = "d")

ax.tick_params(axis="x", rotation=45)                  # rotate x labels so months don't overlap
ax.grid(True, axis="y", linestyle=":", alpha=0.6)      # dotted horizontal gridlines only

least_month, least_value = Tea_trend.idxmin() , Tea_trend.min()
ax.annotate(f"least: {least_value:.0f}",
            xy=(least_month, least_value),                # point the arrow AT
            xytext=(least_month, least_value + 30),        # put the TEXT here
            arrowprops=dict(arrowstyle="->"), ha="center")

ax.set_title("Tea Sales by Month")
plt.show()

3. #Build a 1x2 (not 2x2) subplot grid comparing just Coffee and Tea
fig, axes = plt.subplots(1, 2, figsize=(9, 6))    # axes is a 2x2 array of Axes objects

for ax, cat in zip(axes.flat, ["Tea", "Coffee"]):         # .flat loops through all 4, regardless of shape , cat = category
    trend = df[df.category == cat].groupby("month", sort=False)["daily_sales"].sum().reindex(month_order)
    ax.plot(trend.index, trend.values)
    ax.set_title(cat)
    ax.tick_params(axis="x", rotation=45)

fig.tight_layout()      # auto-adds spacing so titles/labels don't overlap
plt.show()

