# -*- coding: utf-8 -*-
"""tns2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/14LnjNwpD5KBcoWYOqqXNadrUiDZ_ah5j

Seaborn: Relational & Distribution Plots (~25 min) Seaborn is built on matplotlib. It adds nicer defaults, works straight from a DataFrame (data=df, x=..., y=..., hue=...), and ships ready-made statistical charts.

One key idea: most seaborn functions come in two flavors — axes-level (sns.scatterplot, takes ax= and fits into your own grid) and figure-level (sns.relplot, manages its own figure and can facet with col=/row=).
"""

# Commented out IPython magic to ensure Python compatibility.
import numpy as np              # random numbers + array math
import pandas as pd             # DataFrames - the table both libraries plot from
import matplotlib.pyplot as plt # matplotlib
import seaborn as sns           # seaborn (built on matplotlib)

# show plots inline in the notebook:
# %matplotlib inline
np.random.seed(42)               # same "random" numbers every run

# One dataset for the whole notebook: daily sales for a coffee shop chain
dates = pd.date_range("2024-01-01", "2024-12-31", freq="D")   # every day in 2024
cities = ["Boston", "Austin", "Seattle", "Denver"]
categories = ["Coffee", "Tea", "Smoothie", "Pastry"]
price = {"Coffee": 4.5, "Tea": 3.5, "Smoothie": 5.5, "Pastry": 3.0}

rows = []
for d in dates:
    month = d.month
    seasonal_temp = 50 + 30 * np.sin((month - 1) / 12 * 2 * np.pi - np.pi / 2)  # warm in summer, cold in winter
    for city in cities:
        city_offset = {"Boston": -5, "Austin": 15, "Seattle": -8, "Denver": 2}[city]
        temp = seasonal_temp + city_offset + np.random.normal(0, 4)             # this city's temp today
        for cat in categories:
            base = {"Coffee": 220, "Tea": 90, "Smoothie": 60, "Pastry": 130}[cat]
            temp_effect = 0
            if cat == "Smoothie":
                temp_effect = (temp - 60) * 1.8      # smoothies sell more when hot
            elif cat == "Coffee":
                temp_effect = (60 - temp) * 0.9      # coffee sells more when cold
            sales = max(0, base + temp_effect + np.random.normal(0, 18))
            rating = np.clip(np.random.normal(4.2, 0.4), 1, 5)
            num_customers = max(0, sales / price[cat] + np.random.normal(0, 4))
            rows.append([d, city, cat, round(temp, 1), round(sales, 2), round(rating, 2), round(num_customers)])

df = pd.DataFrame(rows, columns=["date", "city", "category", "avg_temp", "daily_sales", "rating", "num_customers"])
df["month"] = df["date"].dt.month_name().str[:3]        # "Jan", "Feb", ...
df["day_of_week"] = df["date"].dt.day_name()             # "Monday", "Tuesday", ...
df["is_weekend"] = df["day_of_week"].isin(["Saturday", "Sunday"])

month_order = ["Jan","Feb","Mar","Apr","May","Jun","Jul","Aug","Sep","Oct","Nov","Dec"]
day_order = ["Monday","Tuesday","Wednesday","Thursday","Friday","Saturday","Sunday"]

print(df.shape)
df.head()

# 1. sns.scatterplot of num_customers (x) vs daily_sales (y), colored by category
# ...

# 2. sns.histplot of "rating", with hue="category"
# ...

# 3. sns.relplot faceted by city AGAIN, but kind="line" instead of the default scatter
#    hint: relplot(..., kind="line")
# ...

sns.set_theme(style="whitegrid")   # switch matplotlib's defaults to seaborn's, for every plot from now on

#1. sns.scatterplot of num_customers (x) vs daily_sales (y), colored by category
fig, ax = plt.subplots(figsize=(7, 4.5))
sns.scatterplot(data=df, x="num_customers", y="daily_sales", hue="category", ax=ax)  # hue -> color by category
ax.set_title("customers vs Sales, by Category")
plt.show()

# 2. sns.histplot of "rating", with hue="category"
fig, ax = plt.subplots(figsize=(8, 5))
sns.histplot(data=df, x="rating", hue="category", kde= True, element="step" ,ax=ax)  # kde=True adds the curve
ax.set_title("rating Distribution by Category")
plt.show()

# 3. sns.relplot faceted by city AGAIN, but kind="line" instead of the default scatter
#    hint: relplot(..., kind="line")
sns.relplot(
    data=df.sample(600, random_state=1), #600 = rondom rows
    x="avg_temp", y="daily_sales",
    hue="category",   # color by category
    col="city",        # one small chart PER CITY
    kind="line",
    col_wrap=2, height=3,
)
plt.show()

